version: '2'
services:
 
  mysql:
    image: mysql:5.7
    container_name: presta_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prestashop
    volumes:
      - ./.docker/data/mysql/:/var/lib/mysql
      - ./.docker/logs/mysql/:/var/log/mysql
    ports:
      - "3306:3306"
  
  app_dev:
    build: .
    container_name: presta_app
    tty: true
    environment:
      - VIRTUAL_HOST=prestashop.test
    volumes : 
      - ./:/var/www/html:rw
    restart: always
    ports:
      - 80:80
    links:
      - "mysql"